#!/usr/bin/env python3
"""Write PROGRESS.md, progress_map.svg and progress.json from objdiff's report.

Run inside the build container after a successful build:

    tools/dock python3 tools/progress.py
    python3 tools/progress.py --no-report      redraw from the existing build/report.json (no container needed)

objdiff-cli compares every unit in objdiff.json (written by configure.py) and reports, per progress category,
how much code is matched: compiled from C/C++ into exactly the original bytes. Assembly-only units count toward
the totals but never as matched. progress_map.svg is the map shown in the top-level README (tools/progress_map.py),
and progress.json feeds its shields.io badge. All three are committed; CI can't regenerate them, because building
needs your own ELF and compiler.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import progress_map  # noqa: E402

REPORT = Path("build/report.json")
OUT = Path("PROGRESS.md")
MAP = Path("progress_map.svg")
BADGE = Path("progress.json")


def pct(part: int, whole: int) -> str:
    return f"{100 * part / whole:.2f}%" if whole else "-"


def row(name: str, m: dict, named: int) -> str:
    code, total = int(m.get("matched_code", 0)), int(m.get("total_code", 0))
    funcs, nfuncs = m.get("matched_functions", 0), m.get("total_functions", 0)
    return (f"| {name} | {funcs:,} / {nfuncs:,} | {pct(funcs, nfuncs)} | {code:,} / {total:,} | {pct(code, total)} "
            f"| {named:,} |")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--no-report", action="store_true", help=f"reuse {REPORT} instead of running objdiff-cli")
    args = p.parse_args()
    if not args.no_report:
        r = subprocess.run(["objdiff-cli", "report", "generate", "-p", ".", "-o", str(REPORT)], cwd=ROOT,
                           capture_output=True, text=True)
        if r.returncode:
            sys.exit(f"objdiff-cli failed:\n{r.stderr}")
    report = json.loads((ROOT / REPORT).read_text())
    config = json.loads((ROOT / "objdiff.json").read_text())
    names = {c["id"]: c["name"] for c in config["progress_categories"]}

    lines = [
        "# Progress",
        "",
        "Generated by `tools/progress.py` from objdiff's report; do not edit by hand. A function counts as matched",
        "when its C/C++ compiles to exactly the original bytes; the build links it once its whole unit matches.",
        "*Named* counts functions identified by name (`config/symbol_addrs.txt`), whether or not they are in C yet.",
        "",
        "| Category | Functions | | Code bytes | | Named |",
        "|---|---|---|---|---|---|",
    ]
    counts = progress_map.named(report)
    for cat in report["categories"]:
        lines.append(row(names.get(cat["id"], cat["id"]), cat["measures"], counts.get(cat["id"], (0, 0))[0]))
    lines.append(row("**All**", report["measures"], counts["all"][0]))
    lines += [
        "",
        "Categories follow the map in [docs/layout.md](docs/layout.md). Hand-written assembly and VU microcode are",
        "expected to stay assembly, as in the original source.",
        "",
    ]
    (ROOT / OUT).write_text("\n".join(lines))
    (ROOT / MAP).write_text(progress_map.render(report))
    (ROOT / BADGE).write_text(json.dumps(progress_map.badge(report), indent=2) + "\n")
    print("\n".join(lines))
    print(f"wrote {OUT}, {MAP} and {BADGE}")


if __name__ == "__main__":
    main()
