#!/usr/bin/env python3
"""Write PROGRESS.md, progress_map.svg and progress.json from objdiff's report.

Run inside the build container after a successful build:

    tools/dock python3 tools/progress.py
    python3 tools/progress.py --no-report      redraw from the existing build/report.json (no container needed)

objdiff-cli compares every unit in objdiff.json (written by configure.py) and reports, per progress category,
how much code is matched: compiled from C/C++ into exactly the original bytes. Only the `game` category contributes
to public completion progress. Unmatched game assembly counts toward its totals; vendor libraries and runtime do not.
progress_map.svg is the map shown in the top-level README (tools/progress_map.py),
and progress.json feeds its shields.io badge. All three are committed; CI can't regenerate them, because building
needs your own ELF and compiler.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import progress_map  # noqa: E402

REPORT = Path("build/report.json")
OUT = Path("PROGRESS.md")
MAP = Path("progress_map.svg")
BADGE = Path("progress.json")


def pct(part: int, whole: int) -> str:
    return f"{100 * part / whole:.2f}%" if whole else "-"


def row(name: str, m: dict, named: int) -> str:
    code, total = int(m.get("matched_code", 0)), int(m.get("total_code", 0))
    funcs, nfuncs = m.get("matched_functions", 0), m.get("total_functions", 0)
    return (f"| {name} | {funcs:,} / {nfuncs:,} | {pct(funcs, nfuncs)} | {code:,} / {total:,} | {pct(code, total)} "
            f"| {named:,} |")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--no-report", action="store_true", help=f"reuse {REPORT} instead of running objdiff-cli")
    args = p.parse_args()
    if not args.no_report:
        r = subprocess.run(["objdiff-cli", "report", "generate", "-p", ".", "-o", str(REPORT)], cwd=ROOT,
                           capture_output=True, text=True)
        if r.returncode:
            sys.exit(f"objdiff-cli failed:\n{r.stderr}")
    report = json.loads((ROOT / REPORT).read_text())
    game = progress_map.report_cat(report, progress_map.GAME_CATEGORY)
    if not game:
        sys.exit("objdiff report has no game category; refusing to publish an unscoped progress report")

    lines = [
        "# PS2 game-source decompilation progress",
        "",
        "Generated by `tools/progress.py` from objdiff's report; do not edit by hand. A function counts as matched",
        "when its C/C++ compiles to exactly the original bytes; the build links it once its whole unit matches.",
        "*Named* counts functions identified by name (`config/symbol_addrs.txt`), whether or not they are in C yet.",
        "",
        "Completion tracks **Burnout 3's game code only** (objdiff category `game`, including carved game units and",
        "game static initializers). Vendor libraries, runtime, startup assembly and VU microcode are outside this",
        "denominator. The complete executable still has to reproduce the original SHA-1 and run in PCSX2.",
        "",
        "| Scope | Matched functions | Function % | Matched code bytes | Code % | Named game functions |",
        "|---|---|---|---|---|---|",
    ]
    counts = progress_map.named(report)
    lines.append(row("**Burnout 3 game code**", game, counts.get(progress_map.GAME_CATEGORY, (0, 0))[0]))
    excluded = [c["measures"] for c in report["categories"] if c["id"] != progress_map.GAME_CATEGORY]
    excluded_functions = sum(int(m.get("total_functions", 0)) for m in excluded)
    excluded_code = sum(int(m.get("total_code", 0)) for m in excluded)
    lines += [
        "",
        "Scope follows the category boundaries in [docs/layout.md](docs/layout.md). Function and byte percentages",
        "measure different things; the visual map and badge use **code bytes**, not the function percentage.",
        "",
        "## Preserved dependencies",
        "",
        f"The vendor/runtime categories contain {excluded_functions:,} functions and {excluded_code:,} code bytes",
        "outside the completion metric: RenderWare graphics and audio, Sony libsce, the C/C++ runtime, EA DirtySock",
        "and Logitech device libraries. Their original assembly is regenerated locally from the user's ELF and",
        "retained in the matching build. Hand-written startup assembly and VU microcode stay assembly.",
        "",
        "Use existing sources and decomps to recover interfaces and guide any useful library matches:",
        "",
        "- **RenderWare graphics/audio and Logitech:** [Burnout 2](https://github.com/b3dllc/burnout2),",
        "  [RenderWare 3.7 source](https://github.com/sigmaco/rwsrc-v3.7.0.2) and",
        "  [Persona 4's matching work](https://github.com/Raikaru/Persona4-Decompilation).",
        "- **Sony libraries/runtime:** [ICO](https://github.com/nathanialf/ico),",
        "  [PS2SDK](https://github.com/ps2dev/ps2sdk) and original newlib/fdlibm/libgcc sources.",
        "- **EA networking:** [partial DirtySDK 4.7.0/5.6.2](https://github.com/deadbeef7/DirtySDK) and",
        "  [later DirtySDK source](https://github.com/kitsilanosoftware/DirtySDK).",
        "",
        "These are references with version/platform gaps, not verified replacements. See",
        "[library-references.md](docs/library-references.md) for findings and the reuse workflow. Full vendor-library",
        "reconstruction and the long-term Rust rewrite are not requirements for this PS2 game-source milestone.",
        "",
    ]
    (ROOT / OUT).write_text("\n".join(lines))
    (ROOT / MAP).write_text(progress_map.render(report))
    (ROOT / BADGE).write_text(json.dumps(progress_map.badge(report), indent=2) + "\n")
    print("\n".join(lines))
    print(f"wrote {OUT}, {MAP} and {BADGE}")


if __name__ == "__main__":
    main()
